### ISSUE TITLE
アイコン設定の際に64x64未満の大きさの画像を弾く

### ISSUE THREAD

**Issue by nozz-mat** [CivilTT/ServerStarter2#36]
# 概要

アイコンに64*64未満の大きさの画像を設定すると、コンソールで
```
[Server thread/ERROR]: Couldn't load server icon java.lang.IllegalStateException: Must be 64 pixels wide at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.1-jre.jar:?] at net.minecraft.server.MinecraftServer.j(SourceFile:788) ~[server-23w33a.jar:?] at java.util.Optional.flatMap(Optional.java:289) ~[?:?] at net.minecraft.server.MinecraftServer.bh(SourceFile:785) ~[server-23w33a.jar:?] at net.minecraft.server.MinecraftServer.w(SourceFile:645) ~[server-23w33a.jar:?] at net.minecraft.server.MinecraftServer.a(SourceFile:263) ~[server-23w33a.jar:?] at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
と言われて反映されないので、設定段階で弾けるなら弾いた方が便利そうです

**Comment by CivilTT** [comment]
ダミー画像の生成は下記のサイトで実行
https://placehold.jp
